### ISSUE TITLE
scrollspy highlighting

### ISSUE THREAD

**Issue by labuve** [eddiewebb/hugo-resume#42]
Hi!

I've been trying to get the navigation link of active page be highlighted, so people could always see which page they are on. I see that resume.js in principle includes the scrollspy functionality, but I couldn't get it working. I've google for troubleshooting and implemented every solution I could find: adding popper.min.js, making sure all id targets are correct, making sure I have correct jquery and bootstrap scripts included. Nothing helped.

So, I was wondering if you could maybe have a suggestion how to make it work.

Thanks!

**Comment by eddiewebb** [comment]
Howdy, I don't have immediate suggestion, the highlighting works on click, will need to dig into why scrolling is not triggering this.

**Comment by Preston12321** [comment]
The issue is with the navigation links themselves.

JQuery expects each link to point to `href="#target"` where `target` is the id of the element that we scroll to. But in `layouts/partials/nav.html`, the links are actually of the format `href="/#target"` (note the forward-slash), causing JQuery to not function properly.

The quick fix would be to change all of the `href` attributes in `layouts/partials/nav.html` to fit the correct format, but in my testing, this actually broke the navigation links on all other pages except the root page, since the links from those pages need the `/` to properly navigate back to the root.

Instead, what fixed this issue for me was to add a separate attribute, `data-target="#target"`, to each nav link in `layouts/partials/nav.html` (replacing `target` with the corresponding id: `about`, `skills`, etc). JQuery also accepts this as a way of specifying the scroll targets, so we can fix scrollspy while not breaking the links from other pages.

Hope this helps!

**Comment by labuve** [comment]
Thanks! This explains it well! :)
